#!/usr/bin/env python3

import sys
import signal


def factorize_number(n):
    factors = []
    i = 2
    while i * i <= n:
        if n % i == 0:
            factors.append((i, n // i))
            n //= i
        else:
            i += 1
    if n > 1:
        factors.append((n, 1))
    return factors


def handle_timeout(signum, frame):
    print("TIME LIMIT EXCEEDED")
    sys.exit(0)


def main():
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        return

    filename = sys.argv[1]

    # Set the timeout value in seconds
    timeout = 5

    # Register the signal handler for timeout
    signal.signal(signal.SIGALRM, handle_timeout)
    signal.alarm(timeout)

    try:
        with open(filename, 'r') as file:
            for line in file:
                n = int(line.strip())
                factorizations = factorize_number(n)
                for factor in factorizations:
                    print("{}={}*{}".format(n, factor[0], factor[1]))
    except FileNotFoundError:
        print("FILE NOT FOUND")
    except ValueError:
        print("Invalid input. The file should contain only valid natural numbers.")

    # Cancel the alarm
    signal.alarm(0)


if __name__ == '__main__':
    main()
